### ISSUE TITLE
Clickhouse migration fails with an unexplained error

### ISSUE THREAD

**Issue by apolik** [yandex/perforator#47]
First off, thanks for sharing such an awesome open-source tool!

I'm trying to deploy Perforator using FluxCD's HelmRelease, and the init container is crashing with an unexplained error

```
kubectl get pods
NAME                                                      READY   STATUS    RESTARTS   AGE
db-0                                                      1/1     Running   0          60m
perforator-operator-release-init-clickhouse-77tna-7vnjq   0/1     Error     0          20m
perforator-operator-release-init-clickhouse-77tna-cg6mq   0/1     Error     0          15m
perforator-operator-release-init-clickhouse-77tna-gtf9d   0/1     Error     0          23m

---

kubectl logs perforator-operator-release-init-clickhouse-77tna-7vnjq
main.go:191: Starting migrations
main.go:171: failed to migrate host clickhouse.mycompany.com: [handshake] unexpected packet [72] from server
```

I tested both the Postgres and ClickHouse connections, and they seem to work fine. But there are no any tables inside ClickHouse and Postgres containers

```
clickhouse:
SHOW TABLES FROM perforator;
Query id: f77368ba-1bf2-4d53-982b-724f288e45ac
Ok.
0 rows in set. Elapsed: 0.001 sec.

---

postgres:
perforator-# /dt
<no-tables>
perforator-# 
```

Also, I tried changing the Helm chart version (0.2.8, 0.2.7, and 0.2.6), but that didn't help

I use Envoy with TLS passthrough as an external LB and NGINX Ingress for internal cluster communication

Perforator configuration:
```
ingress:
  http:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: "5m"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: letsencrypt
    className: "nginx"
    hosts:
      - host: perforator.mycompany.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: web-tls
        hosts:
          - perforator.mycompany.com
  databases:
    postgresql:
      migrations:
        enabled: true
      endpoints:
        - host: "db"
          port: "5432"
      db: "perforator"
      user: "perforator"
      password: "superpass123"
    clickhouse:
      migrations:
        enabled: true
      replicas:
        - "clickhouse.mycompany.com:443"
      db: "perforator"
      user: "perforator"
      password: "superpass123"
    s3:
      buckets:
        # If buckets were created with recommended names
        profiles: "my-perforator-profiles"
        binaries: "my-perforator-binaries"
        taskResults: "my-perforator-tasks"
        binariesGSYM: "my-perforator-gsym"
      endpoint: ""
      accessKey: "access_key"
      secretKey: "secret_key"
  proxy:
    url_prefix: https://perforator.mycompany.com/static/results/
```

cluster info:
k8s distributor: k3s HA
helm version: v3.16.4
fluxcd version: 2.4.0
clickhouse chart version: 8.0.7

**Comment by apolik** [comment]
Fixed. it seems like Clickhouse operates over TCP rather than HTTP. Since Nginx Ingress doesn't support TCP protocol, I generated self-signed certificate and connected to the clickhouse using its service DNS name

clickhouse values.yaml
```
tls:
  enabled: true
  autoGenerated: true
```

perforator values.yaml
```
clickhouse:
  replicas:
    - "clickhouse-release.clickhouse-system.svc.cluster.local:9440"
  insecure: true
```

hope it will help someone
